### ISSUE TITLE
Please add DateTimeOffset overloads

### ISSUE THREAD

**Issue by grosch** [daviddesmet/paseto-dotnet#135]
For all of the things like `IssuedAt` that take a DateTime, would you please add an overload that takes a `DateTimeOffset`?

**Comment by grosch** [comment]
@daviddesmet I see you merged this, thanks, but it doesn't look like you push a new release to NPM

**Comment by daviddesmet** [comment]
@grosch oh yeah, I forgot to push the draft release. It will be available in a couple of minutes at NuGet.org
To mention, you can always grab the latest version from here: https://github.com/daviddesmet/paseto-dotnet/pkgs/nuget/Paseto.Core

It helps to test the latest build before it gets promoted to NuGet.org

**Comment by grosch** [comment]
For my packages I created a workflow that runs on release of type published so that when I create a release it automatically publishes to NuGet.  I stored a nugget api key in the repo secrets and then the workflow just does a `dotnet nugget push` with appropriate flags.

**Comment by daviddesmet** [comment]
Yeah, the workflow does run similarly to what you mentioned. It creates a draft release with the merged PRs and closed issues, and then when you move the draft to publish it triggers the Nuget push. You just need to publish the release whenever you feel appropriate. I like it this way since you have more control over things.
